// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiX0fpbUXCFOqc_d4CfZ2XsPdpjPZos1o',
    appId: '1:586156404078:web:8c5ab29793d40397f3257f',
    messagingSenderId: '586156404078',
    projectId: 'shoppingapp-59c58',
    authDomain: 'shoppingapp-59c58.firebaseapp.com',
    storageBucket: 'shoppingapp-59c58.appspot.com',
    measurementId: 'G-1KH9QL690C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuv5qaVSlfOYn1XX7sfSjwFWo_ovHwTEk',
    appId: '1:586156404078:android:6d87c27b836bb145f3257f',
    messagingSenderId: '586156404078',
    projectId: 'shoppingapp-59c58',
    storageBucket: 'shoppingapp-59c58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeJ4LANXXePyRfBt3QvL1KqQDPwMfExB8',
    appId: '1:586156404078:ios:6c0c235d76732f03f3257f',
    messagingSenderId: '586156404078',
    projectId: 'shoppingapp-59c58',
    storageBucket: 'shoppingapp-59c58.appspot.com',
    iosBundleId: 'com.ecom.eCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeJ4LANXXePyRfBt3QvL1KqQDPwMfExB8',
    appId: '1:586156404078:ios:3159c0897ffb1439f3257f',
    messagingSenderId: '586156404078',
    projectId: 'shoppingapp-59c58',
    storageBucket: 'shoppingapp-59c58.appspot.com',
    iosBundleId: 'com.ecom.eCom.RunnerTests',
  );
}
